server:
  port: 8081

spring:
  cloud:
    gateway:
      routes:
        - id: login-service
            uri: lb://login-service
            predicates:
              - Path=/logins/**
            filters:
              - RewritePath=/(?<logins>.*), /$\{logins}

        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/accounts/**
          filters:
            - RewritePath=/(?<accounts>.*), /$\{accounts}

        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/(?<users>.*), /$\{users}

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/events/**
          filters:
            - RewritePath=/(?<transactions>.*), /$\{transactions}

  application:
    name: gateway


management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/